# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_named packages

frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
http: !include http.yaml
life360: !include life360.yaml
tplink: !include tplink.yaml
template: !include templates.yaml
light: !include lights.yaml

cover: !include_dir_list cover/
group: !include_dir_merge_named group/
input_boolean: !include_dir_merge_named input_boolean/
