unique_id: b89972c2-31fa-43aa-a12c-618178af0927

binary_sensor:
  - name: Garage door open
    unique_id: 47ce057b-4be6-4430-bcdd-824fc006ab16
      # True if the front door is open for more than one minute
    state: >
      {{
        is_state('cover.garage_door', 'open') and
        (is_state('input_boolean.outside_mode', 'off') or is_state('binary_sensor.no_one_home', 'on'))
      }}
    icon: mdi:garage-open
