sensor:
  - platform: rest
    resource: https://api.weather.gov/alerts/active/count
    name: Weather alert count
    value_template: >
      {% if value_json.zones.ILZ013 is defined %}
        {{ value_json.zones.ILZ013 }}
      {% elif value_json.zones.ILC043 is defined %}
        {{ value_json.zones.ILC043 }}
      {% else %}
        0
      {% endif %}
    headers:
      User-Agent: Homeassistant
      Accept: application/ld+json
    scan_interval: 15
