sensor:
  - platform: rest
    resource: https://api.weather.gov/alerts/active?zone=ILZ013,ILC043
    name: Weather alert event
    value_template: >
      {% if value_json.features[0] is defined %}
        {{ value_json['features'][0]['properties'].event }}
      {% else %}
        None
      {% endif %}
    json_attributes:
      - features
    headers:
      User-Agent: Homeassistant
      Accept: application/geo+json
    scan_interval: 15
