automation:
  - alias: Sunrise
    description: Open blinds at sunrise
    mode: single
    trigger:
      - platform: state
        entity_id: sun.sun
        to: above_horizon
    action:
      - service: cover.open_cover
        target:
          entity_id:
            - cover.deck_door_blinds
            - cover.family_room_blinds
            - cover.kitchen_blinds
