automation:
- alias: "Outside mode on"
  description: "Turn off outside mode"
  mode: single
  trigger:
  - platform: state
    entity_id: input_boolean.outside_mode
    to: "on"
  action:
  - service: script.open_up
