automation:
  - alias: Wallmote
    id: e6253bc7-b598-4fa7-9112-a8f5b464acdb
    mode: single
    trigger:
      platform: event
      event_type: zwave_js_value_notification
      event_data:
        domain: zwave_js
        node_id: 26
        command_class_name: "Central Scene"
    action:
      - variables:
          action_name: "{{ trigger.event.data.value }}"
          property_key: "{{ trigger.event.data.property_key }}"
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ action_name == 'KeyPressed' and property_key == '001'}}"
            sequence:
              - service: scene.turn_on
                target:
                  entity_id: scene.feeding
          - conditions:
              - condition: template
                value_template: "{{ action_name == 'KeyHeldDown' and property_key == '001'}}"
            sequence: []
          - conditions:
              - condition: template
                value_template: "{{ action_name == 'KeyPressed' and property_key == '002'}}"
            sequence:
              - service: scene.turn_on
                target:
                  entity_id: scene.sleeping
          - conditions:
              - condition: template
                value_template: "{{ action_name == 'KeyHeldDown' and property_key == '002'}}"
            sequence: []
          - conditions:
              - condition: template
                value_template: "{{ action_name == 'KeyPressed' and property_key == '003'}}"
            sequence:
              - service: light.toggle
                target:
                  entity_id: light.kitchen_skylight
          - conditions:
              - condition: template
                value_template: "{{ action_name == 'KeyHeldDown' and property_key == '003'}}"
            sequence: []
          - conditions:
              - condition: template
                value_template: "{{ action_name == 'KeyPressed' and property_key == '004'}}"
            sequence:
              - service: light.toggle
                target:
                  entity_id:
                    - light.upstairs_bathroom_mirror
                    - light.upstairs_bathroom_shower
          - conditions:
              - condition: template
                value_template: "{{ action_name == 'KeyHeldDown' and property_key == '004'}}"
            sequence: []
