automation:
  - alias: "Daily backup (full)"
    id: 6a02e20c-07d4-47cd-a3b3-b573c75588b0
    description: "Run daily backup and backup purge at 0500"
    mode: single
    trigger:
      - platform: time
        at: "05:00:00"
    action:
      - service: auto_backup.snapshot_full
        data:
          name: "Daily Backup - {{ now().strftime('%Y-%m-%d') }}"
          keep_days: 14
      - service: auto_backup.purge

