automation:
  - alias: Someone leaving
    id: baf6695f-9c77-4920-8f9e-9cec6786398f
    mode: restart
    trigger:
      - platform: state
        entity_id: person.david_gee
        from: home
        to: not_home
      - platform: state
        entity_id: person.monica_gee
        from: home
        to: not_home
      - platform: state
        entity_id: input_select.presence_simulator
        from: home
        to: not_home
    action:
      - choose:
          # If no-one is home then turn off outside mode and lock up
          - conditions:
              - condition: state
                entity_id: binary_sensor.template_noone_home
                state: "on"
            sequence:
              - service: input_boolean.turn_off
                target:
                  entity_id: input_boolean.outside_mode
              - service: script.lock_up
          # Otherwise, lock up if outside mode is off
          - conditions:
              - condition: state
                entity_id: input_boolean.outside_mode
                state: "off"
            sequence:
              - service: script.lock_up
      - choose:
          - conditions:
              # If no-one is home and babysitter mode is off,
              # turn off the lights and resume the thermostat schedule
              - condition: and
                conditions:
                  - condition: state
                    entity_id: binary_sensor.template_noone_home
                    state: "on"
                  - condition: state
                    entity_id: input_boolean.babysitter_mode
                    state: "off"
            sequence:
              - service: scene.turn_on
                target:
                  entity_id: scene.leave_home
              - service: ecobee.resume_program
                data:
                  entity_id: climate.hallway
