automation:
  - alias: TV lightstrip
    description: Set TV lightstrip to colorloop when turned on
    mode: single
    trigger:
      - platform: state
        entity_id: light.family_room_tv_lightstrip
        to: "on"
    action:
      - service: light.turn_on
        target:
          entity_id: light.family_room_tv_lightstrip
        data:
          effect: colorloop
