automation:
  - alias: TV lightstrip
    id: b8a0a71d-e613-4858-ae4d-1c1124a4f752
    description: Set TV lightstrip to colorloop when turned on
    mode: single
    trigger:
      - platform: state
        entity_id: light.family_room_tv_lightstrip
        to: "on"
    action:
      - service: light.turn_on
        target:
          entity_id: light.family_room_tv_lightstrip
        data:
          effect: colorloop
