sensor:
- platform: template
  sensors:
    pihole_ads_blocked_today:
      friendly_name: Total ads blocked today
      value_template: >
        {{
          states('sensor.pi0_ads_blocked_today') | int + states('sensor.pi1_ads_blocked_today') | int
        }}
      icon_template: mdi:close-octagon-outline
