sensor:
- platform: template
  sensors:
    pihole_dns_queries_today:
      friendly_name: Total DNS queries today
      value_template: >
        {{
          states('sensor.pi0_dns_queries_today') | int + states('sensor.pi1_dns_queries_today') | int
        }}
      icon_template: mdi:comment-question-outline
