{% macro door_state(entity_id) -%}{{ 'open' if states(entity_id) == 'on' else 'closed' }}{%- endmacro %}
automation:
- alias: "Notify - deck door left open"
  description: "Send a notification when deck door has been left open for one minute or more"
  mode: single
  trigger:
  - platform: state
      entity_id: binary_sensor.deck_door_sensor
  - platform: time_pattern
    # Every five minutes
    minutes: "/5"
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.outside_mode
      state: off
    - condition: state
      entity_id: binary_sensor.deck_door_sensor
      state: open
      for:
        minutes: 1
  action:
  - service: script.notify_all_mobile_devices
    data:
      title: "{{ state_attr('binary_sensor.deck_door_sensor', 'friendly_name') }}"
      message: "{{ state_attr('binary_sensor.deck_door_sensor', 'friendly_name') }} is now {{ door_state('binary_sensor.deck_door_sensor') }}"
