binary_sensor:
- platform: template
  sensors:
    # True if at the deck door is open for more than one minute
    notify_deck_door_open_alert:
      friendly_name: Deck door open alert
      value_template: "{{ is_state('binary_sensor.deck_door_sensor', 'open') and (now() - states.binary_sensor.deck_door_sensor.last_changed > timedelta(minutes = 1)) }}"
      icon_template: mdi:door-open
