automation:
- alias: "Notify - locks"
  description: "Send a notification when locks are locked or unlocked"
  mode: single
  trigger:
  - platform: state
    entity_id:
    - lock.front_door_lock
  action:
  - service: script.notify_all_mobile_devices
    data:
      title: "{{ trigger.to_state.attributes.friendly_name }}"
      message: "{{ trigger.to_state.attributes.friendly_name }} is now {{ trigger.to_state.state }}"
