automation:
- alias: "Notify - garage door"
  description: "Send a notification when the garage door is opened or closed"
  mode: single
  trigger:
  - platform: state
    entity_id:
    - cover.garage_door
    to:
    - "open"
    - "closed"
  action:
  - service: script.notify_all_mobile_devices
    data:
      title: "{{ trigger.to_state.attributes.friendly_name }}"
      message: "{{ trigger.to_state.attributes.friendly_name }} is now {{ trigger.to_state.state }}"
