binary_sensor:
- platform: template
  sensors:
    # True if at least one person is home
    notify_garage_door_open_alert:
      friendly_name: Garage door open alert
      # Set to true if the number of people with state == home is greater than zero
      value_template: "{{ is_state('cover.garage_door', 'open') and (is_state('input_boolean.outside_mode', 'off') or is_state('binary_sensor.noone_home', 'on')) }}"
      icon_template: mdi:garage-open
