binary_sensor:
- platform: template
  sensors:
    # True if at the front door is open for more than one minute
    notify_front_door_open_alert:
      friendly_name: Front door open alert
      value_template: "{{ is_state('binary_sensor.front_door_sensor', 'open') and (now() - states.binary_sensor.front_door_sensor.last_changed > timedelta(minutes = 1)) }}"
      icon_template: mdi:door-open
