automation:
- alias: "Lighting - daytime"
  description: "Turn on daytime scene"
  mode: single
  trigger:
  - platform: time
    at: "09:00:00"
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.lighting_daytime
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  - service: scene.turn_on
    target:
      entity_id: scene.lighting_weekday_daytime
