automation:
- alias: "Lighting - leave home"
  description: "Turn on the leave home scene when no-one is home"
  mode: single
  trigger:
  # Trigger if no-one home becomes true
  - platform: state
    entity_id: binary_sensor
    to: "on"
  condition:
  - condition: state
    entity_id: input_boolean.babysitter_mode
    state: "off"
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.leave_home
