automation:
- alias: "Lighting - lights out"
  description: "Turn off all lights and fans at midnight"
  mode: single
  trigger:
  - platform: time
    at: "00:00:00"
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.lights_out
