automation:
- alias: "Lighting - arrive home"
  description: "Turn on the arrive home scene when arriving home during darkness"
  mode: single
  trigger:
  - platform: state
    entity_id: input_boolean.presence_someone_arriving
    to: "on"
  condition:
  # Only trigger if the sun is below 7.5°
  # (roughly 30 minutes before/after sunset/sunrise)
  - condition: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: 7.5
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.lighting_arrive_home
