sensor:
- platform: template
  sensors:
    # Maintains a count of the number of people home for use with arrive home
    # and leave home automations
    number_of_people_home:
      friendly_name: Number of people home
      # Set to the number of people with state == home
      value_template: "{{ expand('group.everyone') | selectattr('state', 'equalto', 'home') | list | length }}"
      icon_template: mdi:account-multiple
