binary_sensor:
- platform: template
  sensors:
    # True if no-one is home
    noone_home:
      friendly_name: No-one home
      # Set to true if the number of people with state == home is zero
      value_template: "{{ expand('group.everyone') | selectattr('state', 'equalto', 'home') | list | length == 0 }}"
      icon_template: mdi:account-off
    # True if at least one person is home
    anyone_home:
      friendly_name: Anyone home
      # Set to true if the number of people with state == home is greater than zero
      value_template: "{{ expand('group.everyone') | selectattr('state', 'equalto', 'home') | list | length > 0 }}"
      icon_template: mdi:account-multiple-outline
    # True if everyone is home
    everyone_home:
      friendly_name: Everyone home
      # Set to true if the number of people with state == away is zero
      value_template: "{{ expand('group.everyone') | selectattr('state', 'equalto', 'away') | list | length == 0 }}"
      icon_template: mdi:account-multiple
sensor:
- platform: template
  sensors:
    # Maintains a count of the number of people home for use with arrive home
    # and leave home automations
    number_of_people_home:
      friendly_name: Number of people home
      # Set to the number of people with state == home
      value_template: "{{ expand('group.everyone') | selectattr('state', 'equalto', 'home') | list | length }}"
      icon_template: mdi:account-multiple
