binary_sensor:
- platform: template
  sensors:
    # True if everyone is home
    everyone_home:
      friendly_name: Everyone home
      # Set to true if the number of people with state == away is zero
      value_template: "{{ expand('group.everyone') | selectattr('state', 'equalto', 'away') | list | length == 0 }}"
      icon_template: mdi:account-multiple
