automation:
- alias: Presence - someone arriving
  mode: restart
  trigger:
  - platform: state
    entity_id: person.david_gee
    from: not_home
    to: home
  - platform: state
    entity_id: person.monica_gee
    from: not_home
    to: home
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.presence_someone_arriving
  - delay:
      minutes: 2
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.presence_someone_arriving
