binary_sensor:
- platform: template
  sensors:
    # True if at least one person is home
    anyone_home:
      friendly_name: Anyone home
      # Set to true if the number of people with state == home is greater than zero
      value_template: "{{ expand('group.everyone') | selectattr('state', 'equalto', 'home') | list | length > 0 }}"
      icon_template: mdi:account-multiple-outline
