automation:
- alias: Presence - someone leaving
  mode: restart
  trigger:
  - platform: state
    entity_id: person.david_gee
    from: home
    to: not_home
  - platform: state
    entity_id: person.monica_gee
    from: home
    to: not_home
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.presence_somone_leaving
  - delay:
      minutes: 2
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.presence_somone_leaving
