automation:
  - alias: Presence - someone arriving
    mode: restart
    trigger:
      - platform: state
        entity_id: person.david_gee
        from: not_home
        to: home
      - platform: state
        entity_id: person.monica_gee
        from: not_home
        to: home
      - platform: state
        entity_id: input_select.presence_simulator
        from: not_home
        to: home
    action:
      - service: script.open_up
      - choose:
          # If arriving home at night, also turn some lights on
          - conditions:
              - condition: numeric_state
                entity_id: sun.sun
                attribute: elevation
                below: 7.5
            sequence:
              - service: scene.turn_on
                target:
                  entity_id: scene.arrive_home
