unique_id: f7ac0b8f-5030-4af6-81e2-9977d5609d50

binary_sensor:
  - name: Anyone home
    unique_id: ee6af028-b288-4aa6-b81d-132531136b00
    # Set to true if the number of people with state == home is greater than zero
    state: >
      {{
        expand('group.everyone') |
        selectattr('state', 'equalto', 'home') |
        list |
        length > 0
      }}
    availability: >
      {{
        expand('group.everyone') |
        list |
        length > 0
      }}
    icon: mdi:account-multiple-outline
