unique_id: e2b2a48e-89a9-4b43-87df-c3f0527addd3

binary_sensor:
  - name: Everyone home
    unique_id: 3808b30d-e6eb-4bd5-8323-34c04b06df94
    # Set to true if the number of people with state == away is zero
    state: >
      {{
        expand('group.everyone') |
        selectattr('state', 'equalto', 'away') |
        list |
        length == 0
      }}
    availability: >
      {{
        expand('group.everyone') |
        list |
        length > 0
      }}
    icon: mdi:account-multiple
