unique_id: 60f1aa14-befd-4acb-8c90-2efcb987d6d9

binary_sensor:
  - name: Front door open
    unique_id: ba474bc2-62d0-4c6f-aedd-283f268018d6
      # True if the front door is open for more than one minute
    state: >
      {{
        is_state('binary_sensor.living_room_front_door', 'open') and
        (now() - states.binary_sensor.living_room_front_door.last_changed > timedelta(minutes = 1))
      }}
    icon: mdi:door-open
