unique_id: 90fecc83-1f1a-4ad9-8878-d9c2f9341499

binary_sensor:
  - name: Ground floor fan on
    unique_id: f0de2f9c-9d15-46ab-876b-3d43375d3e4f
    state: >
      {{
        is_state_attr("climate.ground_floor", "fan", "on")
      }}
    icon: mdi:fan
