unique_id: e6ff18fd-0fd5-4d69-a69c-d990f0d0255f

sensor:
  - name: Loft temperature
    unique_id: bbab0cc7-9dad-43de-ab94-5d0abfd34803
    state: >
      {{ state_attr("climate.upstairs", "current_temperature") }}
    device_class: temperature
    unit_of_measurement: °F
