unique_id: cf05ec3d-9171-49cf-bf40-7064e9a770fe

binary_sensor:
  - name: Number of lights on
    unique_id: a8a09b3c-d7cc-4c7d-9d20-cf026a9a2d9a
    state: >
      {%
        set lights = expand(state_attr('light.all_main_lights', 'entity_id')) |
        map(attribute='entity_id') |
        list
      %}
      {{
        states.light |
        selectattr('state', 'eq', 'on') |
        selectattr('entity_id', 'in', lights) |
        list |
        count
      }}
    icon: mdi:lightbulb-group
