unique_id: 7558d895-180b-409d-97f9-c1de6e6af59f

sensor:
  - name: Number of people home
    unique_id: 8fa30698-e2af-4e59-9750-21824ab52a1c
    state: >
      {{
        expand('group.everyone') |
        selectattr('state', 'match', 'home|on') |
        list |
        count
      }}
    icon: mdi:account-group
