unique_id: 7558d895-180b-409d-97f9-c1de6e6af59f

sensor:
  - name: People home
    unique_id: 8fa30698-e2af-4e59-9750-21824ab52a1c
    state: >
      {% set num_ppl = expand('group.everyone') | list | count %}
      {% set num_ppl_home = expand('group.everyone') | selectattr('state', 'eq', 'home') | list | count %}
      {% if num_ppl_home == 0 %}
        {% if is_state('input_boolean.babysitter_mode', 'on') %}
          babysitter
        {% else  %}
          no-one
        {% endif %}
      {% elif num_ppl_home < num_ppl %}
        someone
      {% else %}
        everyone
      {% endif %}
    icon: mdi:account-group
