unique_id: f2f19b52-665a-41ef-8596-ecab8d407011

sensor:
  - name: People home
    unique_id: 12eb0903-67e5-4dcf-9043-88a19d45b954
    state: >
      {% set num_ppl = expand('group.everyone') | list | count %}
      {% set num_ppl_home = expand('group.everyone') | selectattr('state', 'eq', 'home') | list | count %}
      {% if num_ppl_home == 0 %}
        {% if is_state('input_boolean.babysitter_mode', 'on') %}
          babysitter
        {% else  %}
          no-one
        {% endif %}
      {% elif num_ppl_home < num_ppl %}
        someone
      {% else %}
        everyone
      {% endif %}
    icon: mdi:account-group
