alias: Announce front door alert
id: f0733468-d71e-483c-b075-e37da935a0ea

mode: single

trigger:
  - platform: state
    entity_id: binary_sensor.living_room_front_door
    to: "on"
    for:
      seconds: 30

action:
  - service: media_player.volume_set
    data:
      volume_level: 1
    target:
      entity_id: media_player.living_room_echo_dot
  - repeat:
      sequence:
        - service: script.alexa_announce
          data:
            target: media_player.living_room_echo_dot
            message: >
              The front door has been open for {{ relative_time(trigger.to_state.last_changed) }}.
        - delay:
            seconds: 30
      until:
        - condition: state
          entity_id: binary_sensor.living_room_front_door
          state: "off"
  - service: media_player.volume_set
    data:
      volume_level: 0.4
    target:
      entity_id: media_player.living_room_echo_dot
