alias: Announce weather alert
id: 16a46ef5-e760-4af5-998f-5da5cdecc57a

mode: single

trigger:
  - platform: state
    entity_id: sensor.weather_alert_count

condition:
  and:
    - condition: numeric_state
      entity_id: sensor.weather_alert_count
      above: 0
    ## Suppress non-emergency alerts during the night
    - or:
        - condition: state
          entity_id: input_boolean.nighttime_mode
          state: "off"
        - condition: template
          value_template: "{{ 'Warning' in states('sensor.weather_alert_event') }}"

action:
  - service: media_player.volume_set
    target:
      entity_id:
        - media_player.kitchen_echo
    data:
      volume_level: 1
  - service: script.alexa_announce
    data:
      target: all
      message: >
        Attention!. . . Attention!. . . The National Weather Service has
        issued a {{ states('sensor.weather_alert_event') }} for your area.
        It expires at {{ as_timestamp(state_attr('sensor.weather_alert_event', 'features')[0].properties.expires) | timestamp_custom('%-I:%M %p on %-m-%-d-%Y') }}.
  - service: media_player.volume_set
    target:
      entity_id:
        - media_player.kitchen_echo
    data:
      volume_level: 0.33
