alias: Auto lock timer
id: 34e1224e-2026-4f18-bd9f-0217227a033c
description: Manage auto-lock timer

# If any of the triggers occurs again during the delay, restart
mode: restart

trigger:
  - platform: state
    entity_id: binary_sensor.auto_lock

action:
  - if:
      - condition: state
        entity_id: binary_sensor.auto_lock
        state: "on"
    then:
      - service: timer.start
        target:
          entity_id: timer.auto_lock
    else:
      - service: timer.cancel
        target:
          entity_id: timer.auto_lock
