alias: Blinds remotes
id: 30813bf0-22be-4e59-9be4-d41e15b0a8e6

mode: single

trigger:
  - platform: state
    entity_id:
      - sensor.family_room_deck_door_blinds_remote_action
      - sensor.kitchen_blinds_remote_action
      - sensor.family_room_tv_blinds_remote_action
    to:
      - open
      - close

condition: []

action:
  - service: >
      cover.{{ trigger.to_state.state }}_cover
    target:
      entity_id: >
        cover.{{
          trigger.to_state.entity_id |
          regex_replace(
            find="^sensor\.(.+)_remote_action$",
            replace="cover.\\1",
            ignorecase=True
          )
        }}
