alias: Daytime
id: 05be85ef-fd14-4b97-ab52-deaa51d1987e
description: Set daytime scene

mode: single

trigger:
  - platform: time
    at: "09:00:00"

action:
  - service: scene.turn_on
    target:
      entity_id: scene.daytime

  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  - service: scene.turn_on
    target:
      entity_id: scene.weekday_daytime
