alias: Dim lights at night
id: 6372eaab-b9b7-4568-bdaf-e36ede643921
description: Dim lights to 6% (15/255) when turned on during nighttime

mode: parallel

trigger:
  - platform: state
    entity_id:
      - light.upstairs_bathroom_mirror
      - light.upstairs_bathroom_shower
    to: "on"

condition:
  condition: state
  entity_id: input_boolean.nighttime_mode
  state: "on"

action:
  - service: light.turn_on
    target:
      entity_id: "{{ trigger.entity_id }}"
    data:
      brightness: 15
