alias: "Evening"
id: 2b2c0215-2c95-4ff2-acf4-b3fc209f0ad9
description: "Set the evening scene when the sun drops below 7.5° above the horizon"

mode: single

trigger:
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: 7.5

action:
  - service: scene.turn_on
    data:
      entities: scene.evening
