alias: Garage
id: 7aaa5486-c720-4a85-a7ee-c3056254da7f
description: Keep the garage light in sync

mode: single

trigger:
  - platform: state
    entity_id: cover.garage_door

action:
  - if:
      - condition: state
        entity_id: cover.garage_door
        state: open
    then:
      - service: switch.turn_on
        target:
          entity_id: switch.garage_work_light
    else:
      - service: switch.turn_on
        target:
          entity_id: switch.garage_work_light
