alias: Julia's humidifier
id: d7cf8e1b-1192-4b94-abf2-5bff9e5bc138
description: Turn the humidifier power on when switched on

mode: single

trigger:
  - platform: state
    entity_id: switch.julias_bedroom_humidifier
    to: "on"

action:
  - service: remote.send_command
    data:
      command: power
      device: julias_humidifier
    target:
      entity_id: remote.julias_bedroom_remote
