alias: Kitchen
id: 3095a99b-396f-4227-b8fd-4cf5cf97fe14
description: Keep the kitchen lights in sync

mode: single

trigger:
  - platform: state
    entity_id: light.kitchen_skylight

action:
  - service: scene.apply
    data:
      entities:
        light.kitchen_bar:
          state: >
            {{ is_state("light.kitchen_skylight", "on") | iif("on", "off") }}
          brightness: 255
        light.kitchen_counter:
          state: >
            {{ is_state("light.kitchen_skylight", "on") | iif("on", "off") }}
          brightness: 255
        light.kitchen_counter_lightstrip:
          state: >
            {{ (is_state("light.kitchen_skylight", "on")) or (state_attr('sun.sun', 'elevation') < 7.5) | iif("on", "off") }}
          rgb_color:
            - 255
            - 65
            - 0
          color_temp: 250
          brightness: 255
          color_mode: >
            {{ (state_attr('sun.sun', 'elevation') < 7.5) | iif("rgb", "color_temp") }}
        light.kitchen_sink:
          state: >
            {{ is_state("light.kitchen_skylight", "on") | iif("on", "off") }}
          brightness: 255
