alias: Kitchen
id: 3095a99b-396f-4227-b8fd-4cf5cf97fe14
description: Keep the kitchen lights in sync

mode: single

trigger:
  - platform: state
    entity_id: light.kitchen_skylight

action:
  - variables:
      light_state: >
        {{ is_state("light.kitchen_skylight", "on") | iif("on", "off") }}
      color_mode: >
        {{ is_state("light.kitchen_skylight", "off") | iif("rgb", "color_temp") }}
  - choose: !include_dir_list ../choose/kitchen-lights
