alias: Morning
id: 4873afa8-1895-4612-afa8-b5b5f4da15c0
description: Set morning scene

mode: single

trigger:
  - platform: time
    at: "07:00:00"

action:
  # Resume kitchen lights sync if daytime
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.nighttime_mode
  - service: scene.turn_on
    target:
      entity_id: scene.morning_common

  - choose: !include_dir_list ../automation-choose/morning-scenes
