alias: Keep Nabu Casa warmed up
id: 91d9851b-3428-44a7-ba70-7a514d8abdb3

mode: single

trigger:
  - platform: webhook
    id: nabu_casa_warmup
    webhook_id: nabu_casa_warmup

condition: []

action:
  - alias: Wait for trigger
    wait_for_trigger: []
