alias: "Outside mode on"
id: 44bb74bb-a9e7-4429-b14d-6d4faf2f00a7
description: "Unlock front door and open garage door when outside mode turned on"

mode: single

trigger:
  - platform: state
    entity_id: input_boolean.outside_mode
    to: "on"

action:
  - service: script.open_up
