alias: Party mode
id: c3848076-9ba7-4063-ae20-f6b646d88850

mode: single

trigger:
  - platform: state
    entity_id: input_boolean.party_mode

action:
  - service: >
      {{ is_state("input_boolean.party_mode", "off") | iif("cover.close_cover", "cover.open_cover") }}
    target:
      entity_id:
        - cover.family_room_deck_door_blinds
  - service: >
      {{ is_state("input_boolean.party_mode", "off") | iif("light.turn_off"", "light.turn_on") }}
    target:
      entity_id:
        - light.outside_gazebo
