alias: Party mode
id: c3848076-9ba7-4063-ae20-f6b646d88850

mode: single

trigger:
  - platform: state
    entity_id: input_boolean.party_mode

action:
  - service: >
      {{ "cover.close_cover" if is_state("input_boolean.party_mode", "off") else "cover.open_cover" }}
    target:
      entity_id:
        - cover.family_room_deck_door_blinds
  - service: >
      {{ "light.turn_off" if is_state("input_boolean.party_mode", "off") else "light.turn_on" }}
    target:
      entity_id:
        - light.outside_gazebo
