alias: Presence manager
id: baf6695f-9c77-4920-8f9e-9cec6786398f
description: Presence manager

mode: queued

trigger:
  - platform: state
    entity_id: zone.home

# Only trigger for legit changes (ignore unavailable),
# and do not trigger during the night or when away
condition:
  - and:
      - condition: template
        value_template: >
          {{ trigger.from_state.state != "unavailable" }}
      - condition: template
        value_template: >
          {{ trigger.to_state.state != "unavailable" }}
      - condition: state
        entity_id: input_boolean.nighttime_mode
        state: "off"
      - condition: state
        entity_id: input_boolean.away_mode
        state: "off"

action:
  - variables:
      arriving: >
        {{
          (trigger.to_state.state | int) >
          (trigger.from_state.state | int)
        }}
      departing: >
        {{
          (trigger.to_state.state | int) <
          (trigger.from_state.state | int)
        }}
  - choose: !include_dir_list ../choose/presence-manager
