alias: Presence manager
id: baf6695f-9c77-4920-8f9e-9cec6786398f
description: Presence manager

mode: queued

trigger:
  - platform: state
    entity_id: sensor.number_of_people_home

action:
  - variables:
      arriving: >
        {{
          (trigger.to_state.state | int) >
          (trigger.from_state.state | int)
        }}
  - choose: !include_dir_list ../automation-choose/presence-manager
