alias: Show persistent weather alert notification
id: fc965ca8-10d3-4d0c-8d73-d2583db82971

mode: single

trigger:
  platform: state
  entity_id: sensor.weather_alert_count

action:
  # Dismiss any current alert so the UI isn"t filled up with these if
  # there are more than one. Only show the latest alert.
  - service: persistent_notification.dismiss
    data:
      notification_id: weather_alert
    ## Create a new persistant notification in the UI for a new alert
  - if:
      - condition: numeric_state
        entity_id: sensor.weather_alert_count
        above: 0
    then:
      - service: persistent_notification.create
        data_template:
          notification_id: weather_alert
          message: >
            {{ state_attr("sensor.weather_alert_event", "features")[0].properties.description }}
          title: >
            {{ states("sensor.weather_alert_event") }}
