alias: Someone leaving
id: baf6695f-9c77-4920-8f9e-9cec6786398f
description: Someone leaving

mode: restart

trigger:
  - platform: state
    entity_id: sensor.number_of_people_home

action: !include_dir_list ../presence-manager
