alias: Sunrise
id: 823e0ae7-8900-4fb5-aa3c-3e9b104e8e08
description: Open blinds at sunrise

mode: single

trigger:
  - platform: state
    entity_id: sun.sun
    to: above_horizon

action:
  - service: cover.open_cover
    target:
      entity_id:
        - cover.deck_door_blinds
        - cover.family_room_deck_door_blinds
        - cover.family_room_tv_blinds
        - cover.kitchen_blinds
