alias: Sunset
id: a16c04b7-28e6-4a71-8a95-02a69609ab72
description: Close blinds at sunset

mode: single

trigger:
  - platform: state
    entity_id: sun.sun
    to: below_horizon

action:
  # If party mode is off, close all blinds
  # If party mode is on, close all blinds except the deck door blinds
  - service: cover.close_cover
    target:
      entity_id: >
        cover.{{ is_state('input_boolean.party_mode', 'on') | iif("all_blinds_non_party_mode", "all_blinds") }}
