alias: Time of day
id: 5c04b503-0cfc-4b2d-bc0f-d15a3e2f54d7

mode: single

trigger:
  - id: sunrise
    platform: numeric_state
    entity_id: sun.sun
    above: 0
  - id: morning
    platform: time
    at: "07:00:00"
  - id: daytime
    platform: time
    at: "09:00:00"
  - id: afternoon
    platform: numeric_state
    entity_id: sun.sun
    below: 7.5
  - id: sunset
    platform: numeric_state
    entity_id: sun.sun
    below: 0
  - id: bedtime
    platform: time
    at: "22:00:00"
  - id: night
    platform: time
    at: "00:00:00"

action:
  - choose: !include_dir_list ../choose/time_of_day
