unique_id: 7138979d-1ce4-4067-914e-53fb06ec7165

sensor:
  - name: Number of second floor lights on
    unique_id: d8b51152-8194-4675-a435-55147d393b5d
    state: >
      {%
        set lights_on = expand('light.all_exterior_lights') |
        selectattr('state', 'eq', 'on') |
        list |
        count
      %}
      {{ iif(lights_on == 0, 'All off', lights_on | string + ' on') }}
    icon: mdi:lightbulb-group
