unique_id: cf05ec3d-9171-49cf-bf40-7064e9a770fe

sensor:
  - name: Number of ground floor lights on
    unique_id: a8a09b3c-d7cc-4c7d-9d20-cf026a9a2d9a
    state: >
      {%
        set lights_on = expand('light.all_ground_floor_lights') |
        selectattr('state', 'eq', 'on') |
        list |
        count
      %}
      {{ iif(lights_on == 0, 'All off', lights_on | string + ' on') }}
    icon: mdi:lightbulb-group
