unique_id: b49b7cf2-9d30-41ed-826b-a9cc05c6c3b7

sensor:
  - name: Time of day - time-based
    unique_id: 093f0e55-3242-422b-8502-91f65a0a7d77
    state: >
      {% set midnight = today_at("00:00") %}
      {% set midnight_tomorrow = midnight + timedelta(days = 1) %}
      {% set zeroseven_hundred = today_at("07:00") %}
      {% set zeroeight_thirty = today_at("08:30") %}
      {% set twentytwo_hundred = today_at("22:00") %}
      {% set time_now = now() %}
      {% set rising = is_state_attr("sun.sun", "rising", true) %}
      {% set elevation = state_attr("sun.sun", "elevation") | float %}
      {% set time_map = {
        midnight <= time_now < zeroseven_hundred: "Nighttime",
        zeroseven_hundred <= time_now < zeroeight_thirty: "Morning",
        zeroeight_thirty <= time_now < twentytwo_hundred: "Daytime",
        twentytwo_hundred <= time_now < midnight_tomorrow: "Bedtime"
      }
      %}
      {{ time_map.get(True) }}
  - name: Time of day - sun-based
    unique_id: cf0b9b63-1645-491b-9e8f-4c6eeaa1eb05
    state: >
      {% set time_now = now() %}
      {% set rising = is_state_attr("sun.sun", "rising", true) %}
      {% set elevation = state_attr("sun.sun", "elevation") | float %}
      {% set time_map = {
        elevation <= 0: "Sunset",
        elevation > 0 and elevation <= 7.5 and rising == true: "Sunrise",
        elevation > 7.5: "Sunrise",
        elevation > 0 and elevation <= 7.5 and rising == false: "Pre-sunset",
      }
      %}
      {{ time_map.get(True) }}

select:
  - name: Time of day - time-based
    unique_id: 42551777-fe22-42b4-8a4b-b57bf807e716
    state: >
      {% set midnight = today_at("00:00") %}
      {% set midnight_tomorrow = midnight + timedelta(days = 1) %}
      {% set zeroseven_hundred = today_at("07:00") %}
      {% set zeroeight_thirty = today_at("08:30") %}
      {% set twentytwo_hundred = today_at("22:00") %}
      {% set time_now = now() %}
      {% set rising = is_state_attr("sun.sun", "rising", true) %}
      {% set elevation = state_attr("sun.sun", "elevation") | float %}
      {% set time_map = {
        midnight <= time_now < zeroseven_hundred: "Nighttime",
        zeroseven_hundred <= time_now < zeroeight_thirty: "Morning",
        zeroeight_thirty <= time_now < twentytwo_hundred: "Daytime",
        twentytwo_hundred <= time_now < midnight_tomorrow: "Bedtime"
      }
      %}
      {{ time_map.get(True) }}
    options:
      - Nighttime
      - Morning
      - Daytime
      - Bedtime
