unique_id: b49b7cf2-9d30-41ed-826b-a9cc05c6c3b7

sensor:
  - name: Time of day
    unique_id: 093f0e55-3242-422b-8502-91f65a0a7d77
    state: >
      {% set midnight = today_at("00:00") %}
      {% set midnight_tomorrow = midnight + timedelta(days = 1) %}
      {% set zeroseven_hundred = today_at("07:00") %}
      {% set zeroeight_thirty = today_at("08:30") %}
      {% set twentytwo_hundred = today_at("22:00") %}
      {% set time_now = now() %}
      {% set time_map = {
        midnight <= time_now < zeroseven_hundred: "Nighttime",
        zeroseven_hundred <= time_now < zeroeight_thirty: "Morning",
        zeroeight_thirty <= time_now < twentytwo_hundred: "Daytime",
        twentytwo_hundred <= time_now < midnight_tomorrow: "Bedtime"
      }
      %}
      {{ time_map.get(True) }}
