binary_sensor:
  - platform: template
    sensors:
      # True if at the front door is open for more than one minute
      template_front_door_open:
        friendly_name: Front door open
        value_template: "{{ is_state('binary_sensor.living_room_front_door', 'open') and (now() - states.binary_sensor.living_room_front_door.last_changed > timedelta(minutes = 1)) }}"
        icon_template: mdi:door-open
