binary_sensor:
  - platform: template
    sensors:
      # True if at the garage door is open and either outside mode is off or no-one is home
      template_garage_door_open:
        friendly_name: Garage door open
        value_template: "{{ is_state('cover.garage_door', 'open') and (is_state('input_boolean.outside_mode', 'off') or is_state('binary_sensor.noone_home', 'on')) }}"
        icon_template: mdi:garage-open
