binary_sensor:
  - platform: template
    sensors:
      # True if at the deck door is open for more than one minute
      template_deck_door_open:
        friendly_name: Deck door open
        value_template: "{{ is_state('binary_sensor.deck_door_sensor', 'open') and (now() - states.binary_sensor.deck_door_sensor.last_changed > timedelta(minutes = 1)) }}"
        icon_template: mdi:door-open
