automation:

- alias: "Open up on arrival"
  description: "Open the garage door and unlock the front door when anyone arrives home"
  mode: single

  trigger:

  - platform: state

    # Trigger when any member of group.everyone changes from away to home
    # The group state can't be used because it's an aggregate value
    entity_id: "{{ expand('group.everyone')  | map(attribute='entity_id') | list }}"
    from: not_home
    to: home

  action:

  - service: cover.open
    target:
      entity_id: cover.garage_door

  - service: lock.unlock
    target:
      entity_id: lock.front_door_lock

