automation:
- alias: "Doors & locks - arrive home"
  description: "Open the garage door and unlock the front door when anyone arrives home"
  mode: single
  trigger:
  - platform: state
    entity_id: input_boolean.presence_someone_arriving
    to: "on"
  action:
  - service: script.doors_and_locks_open_up
