automation:
- alias: "Doors & locks - outside mode"
  description: "Turn off outside mode"
  mode: single
  trigger:
  - platform: state
    entity_id: binary_sensor.noone_home
    to: "on"
  - platform: time
    at: "22:00:00"
  action:
  - service: script.doors_and_locks_lock_up
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.outside_mode
