automation:
- alias: "Doors & locks - leave home"
  description: "Close the garage door and lock the front door on leaving"
  mode: single
  trigger:
  - platform: state
    entity_id: sensor.number_of_people_home
  condition:
  # Only trigger if the number of people home has decreased
  # and outside mode is off
    condition: and
    conditions:
    - condition: template
      value_template: "{{ (trigger.to_state.state | int) < (trigger.from_state.state | int) }}"
    - condition: state
      entity_id: input_boolean.outside_mode
      state: "off"
  action:
  - service: cover.close_cover
    target:
      entity_id: cover.garage_door
  - service: lock.lock
    target:
      entity_id: lock.front_door_lock
