automation:
- alias: "Doors & locks - leave home"
  description: "Close the garage door and lock the front door on leaving"
  mode: single
  trigger:
  - platform: state
    entity_id: input_boolean.presence_someone_leaving
    to: "on"
  condition:
  # Only execute if outside mode is off
  - condition: state
    entity_id: input_boolean.outside_mode
    state: "off"
  action:
  - service: script.doors_and_locks_lock_up
