automation:
- alias: "Doors & locks - lock up"
  description: "Close the garage door and lock the front door at 2200"
  mode: single
  trigger:
  - platform: time
    at: "22:00:00"
  action:
  - service: script.lock_up
