automation:
- alias: "Doors & locks - outside mode on"
  description: "Turn off outside mode"
  mode: single
  trigger:
  - platform: state
    entity_id: input_boolean.outside_mode
    to: "on"
  action:
  - service: script.doors_and_locks_open_up
